/*
** EPITECH PROJECT, 2023
** B-MUL-200-PAR-2-1-myrpg-martin.fillon
** File description:
** components
*/

#ifndef COMPONENTS_H_
    #define COMPONENTS_H_

    #include <SFML/Config.h>

    #include "myrpg/components/defs.h"
    #include "myrpg/components/types.h"
    #include "myrpg/components/component_ids.h"

    #include "myrpg/components/defs.h"
    #include "myrpg/components/types.h"
    #include "myrpg/components/component_ids.h"

static const component_t COMPONENTS[] = {
    {
        .config_file = "./conf/main_menu/background.json",
        .name = "main_menu_background",
        .id = MAIN_MENU_BACKGROUND,
        .type = SPRITE,
        .show = sfTrue,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/main_menu/play.json",
        .name = "main_menu_play_btn",
        .id = MAIN_MENU_PLAY_BTN,
        .type = ANIM_SPRITE,
        .show = sfTrue,
        .init = &init_anim_sprite,
        .draw = &draw_main_menu_button,
        .destroy = &destroy_anim_sprite,
    },
    {
        .config_file = "./conf/main_menu/quit.json",
        .name = "main_menu_quit_btn",
        .id = MAIN_MENU_QUIT_BTN,
        .type = ANIM_SPRITE,
        .show = sfTrue,
        .init = &init_anim_sprite,
        .draw = &draw_main_menu_button,
        .destroy = &destroy_anim_sprite,
    },
    {
        .config_file = "./conf/main_menu/help.json",
        .name = "main_menu_help_btn",
        .id = MAIN_MENU_HELP_BTN,
        .type = ANIM_SPRITE,
        .show = sfTrue,
        .init = &init_anim_sprite,
        .draw = &draw_main_menu_button,
        .destroy = &destroy_anim_sprite,
    },
    {
        .config_file = "./conf/main_menu/settings.json",
        .name = "main_menu_settings_btn",
        .id = MAIN_MENU_SETTINGS_BTN,
        .type = ANIM_SPRITE,
        .show = sfTrue,
        .init = &init_anim_sprite,
        .draw = &draw_main_menu_button,
        .destroy = &destroy_anim_sprite,
    },
    {
        .config_file = "./conf/main_menu/portal.json",
        .name = "main_menu_portal",
        .id = MAIN_MENU_PORTAL,
        .type = ANIM_SPRITE,
        .show = sfTrue,
        .init = &init_main_menu_portal,
        .draw = &draw_main_menu_portal,
        .destroy = &destroy_anim_sprite,
    },
    // !MAIN_MENU


    // HELP
    {
        .config_file = "./conf/main_menu/help/background.json",
        .name = "save_menu_background",
        .id = HELP_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/main_menu/help/back.json",
        .name = "save_menu_background",
        .id = HELP_BACK,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !HELP


    // SAVE_MENU
    {
        .config_file = "./conf/save_menu/background.json",
        .name = "save_menu_background",
        .id = SAVE_MENU_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/load_1.json",
        .name = "save_menu_background",
        .id = SAVE_MENU_LOAD_1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/load_2.json",
        .name = "save_menu_background",
        .id = SAVE_MENU_LOAD_2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/load_3.json",
        .name = "save_menu_background",
        .id = SAVE_MENU_LOAD_3,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/slot_1.json",
        .name = "save_menu_slot_1",
        .id = SAVE_MENU_SLOT_1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/slot_2.json",
        .name = "save_menu_slot_2",
        .id = SAVE_MENU_SLOT_2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/slot_3.json",
        .name = "save_menu_slot_3",
        .id = SAVE_MENU_SLOT_3,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/save_menu/back.json",
        .name = "save_menu_back_btn",
        .id = SAVE_MENU_BACK_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !SAVE_MENU


    // SELECT_SKIN
    {
        .config_file = "./conf/select_skin/background.json",
        .name = "select_skin_background",
        .id = SELECT_SKIN_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_skin/prev.json",
        .name = "select_skin_prev_btn",
        .id = SELECT_SKIN_PREV_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_skin/next.json",
        .name = "select_skin_next_btn",
        .id = SELECT_SKIN_NEXT_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_skin/skins.json",
        .name = "select_skin_skins",
        .id = SELECT_SKIN_SKINS,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_skin/select.json",
        .name = "select_skin_select_btn",
        .id = SELECT_SKIN_SELECT_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_skin/back.json",
        .name = "select_skin_back_btn",
        .id = SELECT_SKIN_BACK_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !SELECT_SKIN

    // SETTINGS
    {
        .config_file = "./conf/settings/background.json",
        .name = "settings_background",
        .id = SETTINGS_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/audio.json",
        .name = "settings_audio_btn",
        .id = SETTINGS_AUDIO_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/video.json",
        .name = "settings_video_btn",
        .id = SETTINGS_VIDEO_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/key_map.json",
        .name = "settings_key_map_btn",
        .id = SETTINGS_KEY_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/back.json",
        .name = "settings_back_btn",
        .id = SETTINGS_BACK_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/settings_video.json",
        .name = "settings_video",
        .id = SETTINGS_VIDEO,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/settings_audio.json",
        .name = "settings_audio",
        .id = SETTINGS_AUDIO,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/video/settings_fullscreen.json",
        .name = "settings_video_fullscreen",
        .id = SETTINGS_VIDEO_FULLSCREEN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/video/settings_windowed.json",
        .name = "settings_video_windowed",
        .id = SETTINGS_VIDEO_WINDOWED,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/video/settings_30_fps.json",
        .name = "settings_30_fps",
        .id = SETTINGS_VIDEO_30_FPS,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/video/settings_60_fps.json",
        .name = "settings_60_fps",
        .id = SETTINGS_VIDEO_60_FPS,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/video/settings_144_fps.json",
        .name = "settings_144_fps",
        .id = SETTINGS_VIDEO_144_FPS,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    }, {
        .config_file = "./conf/settings/audio/music.json",
        .name = "settings_audio_music",
        .id = SETTINGS_AUDIO_MUSIC,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text,
    }, {
        .config_file = "./conf/settings/audio/sound.json",
        .name = "settings_audio_sound",
        .id = SETTINGS_AUDIO_SOUND,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text,
    }, {
        .config_file = "./conf/settings/audio/settings_minus_music.json",
        .name = "settings_audio_minus_music",
        .id = SETTINGS_AUDIO_MINUS_MUSIC,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    }, {
        .config_file = "./conf/settings/audio/settings_plus_music.json",
        .name = "settings_audio_plus_music",
        .id = SETTINGS_AUDIO_PLUS_MUSIC,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    }, {
        .config_file = "./conf/settings/audio/settings_minus_sound.json",
        .name = "settings_audio_minus_sound",
        .id = SETTINGS_AUDIO_MINUS_SOUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    }, {
        .config_file = "./conf/settings/audio/settings_plus_sound.json",
        .name = "settings_audio_plus_sound",
        .id = SETTINGS_AUDIO_PLUS_SOUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/settings/keys/up/box.json",
        .name = "up_box",
        .id = SETTINGS_KEYS_UP_BOX,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite
    },
    {
        .config_file = "./conf/settings/keys/up/text.json",
        .name = "up_text",
        .id = SETTINGS_KEYS_UP_TEXT,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/up/key.json",
        .name = "up_key",
        .id = SETTINGS_KEYS_UP_KEY,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/down/box.json",
        .name = "down_box",
        .id = SETTINGS_KEYS_DOWN_BOX,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite
    },
    {
        .config_file = "./conf/settings/keys/down/text.json",
        .name = "down_text",
        .id = SETTINGS_KEYS_DOWN_TEXT,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/down/key.json",
        .name = "down_key",
        .id = SETTINGS_KEYS_DOWN_KEY,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/right/box.json",
        .name = "right_box",
        .id = SETTINGS_KEYS_RIGHT_BOX,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite
    },
    {
        .config_file = "./conf/settings/keys/right/text.json",
        .name = "right_text",
        .id = SETTINGS_KEYS_RIGHT_TEXT,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/right/key.json",
        .name = "right_key",
        .id = SETTINGS_KEYS_RIGHT_KEY,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/left/box.json",
        .name = "left_box",
        .id = SETTINGS_KEYS_LEFT_BOX,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite
    },
    {
        .config_file = "./conf/settings/keys/left/text.json",
        .name = "left_text",
        .id = SETTINGS_KEYS_LEFT_TEXT,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/left/key.json",
        .name = "left_key",
        .id = SETTINGS_KEYS_LEFT_KEY,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/interact/box.json",
        .name = "up_box",
        .id = SETTINGS_KEYS_INTERACT_BOX,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite
    },
    {
        .config_file = "./conf/settings/keys/interact/text.json",
        .name = "interact_text",
        .id = SETTINGS_KEYS_INTERACT_TEXT,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    {
        .config_file = "./conf/settings/keys/interact/key.json",
        .name = "interact_key",
        .id = SETTINGS_KEYS_INTERACT_KEY,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text
    },
    // !SETTINGS

    // HUB
    {
        .config_file = "./conf/hub/environnement/background.json",
        .name = "hub_map",
        .id = HUB_MAP,
        .type = GAME_MAP,
        .show = sfFalse,
        .init = &init_game_map,
        .draw = &draw_hub_map,
        .destroy = &destroy_game_map,
    },
    {
        .config_file = "./conf/hub/environnement/portal.json",
        .name = "hub_portal",
        .id = HUB_PORTAL,
        .show = sfFalse,
        .init = &init_main_menu_portal,
        .draw = &draw_portal,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/npc/beth.json",
        .name = "beth",
        .id = HUB_BETH,
        .type = NPC,
        .show = sfFalse,
        .init = &init_npc,
        .draw = &draw_sprite,
        .destroy = &destroy_npc,
    },
    {
        .config_file = "./conf/hub/enemy/jerry.json",
        .name = "jerry",
        .id = HUB_JERRY,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/npc/birdman.json",
        .name = "birdman",
        .id = HUB_BIRDMAN,
        .type = NPC,
        .show = sfFalse,
        .init = &init_npc,
        .draw = &draw_sprite,
        .destroy = &destroy_npc,
    },
    {
        .config_file = "./conf/hub/npc/summer.json",
        .name = "summer",
        .id = HUB_SUMMER,
        .type = NPC,
        .show = sfFalse,
        .init = &init_npc,
        .draw = &draw_sprite,
        .destroy = &destroy_npc,
    },
    {
        .config_file = "./conf/hub/npc/portal_gun.json",
        .name = "portal_gun",
        .id = HUB_PORTAL_GUN,
        .type = NPC,
        .show = sfFalse,
        .init = &init_npc,
        .draw = &draw_portal_gun,
        .destroy = &destroy_npc,
    },
    {
        .config_file = "./conf/hub/environnement/vignette.json",
        .name = "hub_vignette effect",
        .id = HUB_VIGNETTE,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !HUB


    // SELECT_MAP
    {
        .config_file = "./conf/select_map/background.json",
        .name = "select_map_background",
        .id = SELECT_MAP_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_map/planet_1.json",
        .name = "select_map_planet_1",
        .id = SELECT_MAP_PLANET_1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_map/back.json",
        .name = "select_map_planet_1",
        .id = SELECT_MAP_BACK,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },

    {
        .config_file = "./conf/select_map/planet_2.json",
        .name = "select_map_planet_2",
        .id = SELECT_MAP_PLANET_2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_map/planet_3.json",
        .name = "select_map_planet_3",
        .id = SELECT_MAP_PLANET_3,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !SELECT_MAP


    // PROCEDURAL_MAP
    {
        .config_file = "./conf/procedural_map/map.json",
        .name = "procedural_map",
        .id = GAME_PROCEDURAL_MAP,
        .type = GAME_PMAP,
        .show = sfFalse,
        .init = &init_procedural_map,
        .draw = &draw_procedural_map,
        .destroy = &destroy_procedural_map,
    },
    {
        .config_file = "./conf/procedural_map/enemy/enemies.json",
        .name = "procedural_map_enemies",
        .id = GAME_PROCEDURAL_MAP_ENEMYS,
        .type = ENEMY,
        .show = sfFalse,
        .init = &init_enemies,
        .draw = &draw_enemy,
        .destroy = &destroy_enemies,
    },
    // !PROCEDURAL_MAP


    // IN_GAME_MENU
    {
        .config_file = "./conf/hub/in_game_menu/icon.json",
        .name = "GAME_MENU_ICON",
        .id = GAME_MENU_ICON,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/icon_settings.json",
        .name = "GAME_SETTINGS_ICON",
        .id = GAME_SETTINGS_ICON,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/background.json",
        .name = "background",
        .id = GAME_MENU_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_btn.json",
        .name = "inventory",
        .id = GAME_MENU_INVENTORY_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/quest_btn.json",
        .name = "quest",
        .id = GAME_MENU_QUEST_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/bestiare_btn.json",
        .name = "bestiare",
        .id = GAME_MENU_BESTIARY_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/skin_btn.json",
        .name = "skin",
        .id = GAME_MENU_SKIN_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/back.json",
        .name = "back",
        .id = GAME_MENU_BACK_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/quit_btn.json",
        .name = "back",
        .id = GAME_MENU_QUIT_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/left_inventory.json",
        .name = "back",
        .id = GAME_MENU_LEFT,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/stat.json",
        .name = "back",
        .id = GAME_MENU_STAT,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/skin.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_SKIN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/atck_stat.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_BAR_ATK,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_character_stats,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/hp_stat.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_BAR_HP,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_character_stats,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/shield_stat.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_BAR_SHIELD,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_character_stats,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/drunk_stat.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_BAR_DRUNK,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_character_stats,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_1.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_2.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_3.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_3,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_4.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_4,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_5.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_5,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_6.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_6,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/inventory_box_7.json",
        .name = "STAT_SKIN",
        .id = GAME_MENU_INVENTORY_BOX_7,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !IN_GAME_MENU


    // SKIN_GAME
    {
        .config_file = "./conf/select_skin/in_game_select.json",
        .name = "select_skin_select_btn",
        .id = IN_GAME_SKIN_SELECT_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/select_skin/in_game_back.json",
        .name = "select_skin_back_btn",
        .id = IN_GAME_SKIN_BACK_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !SKIN_GAME


    // QUEST
    {
        .config_file = "./conf/quest/icon_sword.json",
        .name = "icon_sword",
        .id = QUEST_ICON_SWORD,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/quest/quests.json",
        .name = "quests",
        .id = QUESTS,
        .type = QUEST,
        .show = sfFalse,
        .init = &init_quests,
        .draw = &draw_quests,
        .destroy = &destroy_quests,
    },
    // !QUEST


    // BESTIARY
    {
        .config_file = "./conf/bestiary/background.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_1.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_2.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_3.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_3,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_4.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_4,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_5.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_5,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_6.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_6,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_7.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_7,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_8.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_8,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_9.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_9,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_10.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_10,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_11.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_11,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_12.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_12,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_13.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_13,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_14.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_14,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/enemy_15.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_15,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/moon_morty.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_MOON,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/sun_morty.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_SUN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/morty_mecha.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_MECHA,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/morty_rabbit.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_RABBIT,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/morty_motion.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_MOTION,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/bestiary/boss.json",
        .name = "select_skin_back_btn",
        .id = BESTIARY_BOSS,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !BESTIARY


    //SHOP
    {
        .config_file = "./conf/hub/shop/background.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/beth_seller.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BETH,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/boost_atck_1.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BOOST_ATCK1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
        {
        .config_file = "./conf/hub/shop/boost_atck_2.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BOOST_ATCK2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/boost_hp_1.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BOOST_HP1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
        {
        .config_file = "./conf/hub/shop/boost_hp_2.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BOOST_HP2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/boost_shield_1.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BOOST_SHIELD1,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
        {
        .config_file = "./conf/hub/shop/boost_shield_2.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BOOST_SHIELD2,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/buy_btn.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BUY_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/back.json",
        .name = "select_skin_back_btn",
        .id = SHOP_BACK_BTN,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/shop/money_counter.json",
        .name = "select_skin_back_btn",
        .id = SHOP_MONEY_COUNTER,
        .type = TEXT,
        .show = sfFalse,
        .init = &init_text,
        .draw = &draw_text,
        .destroy = &destroy_text,
    },
    //!SHOP

    // MAIN_CHARACTER
    {
        .config_file = "./conf/character/main_character.json",
        .name = "main_character",
        .id = MAIN_CHARACTER,
        .type = CHARACTER,
        .show = sfFalse,
        .init = &init_character,
        .draw = &draw_sprite,
        .destroy = &destroy_anim_sprite,
    },
    {
        .config_file = "./conf/particles/smoke_particle.json",
        .name = "smoke_particle",
        .id = MOVING_SMOKE_PARTICLE,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/hub/in_game_menu/dead_plate.json",
        .name = "smoke_particle",
        .id = DEATH_ANIMATION,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    // !MAIN_CHARACTER

    // PROJECTILE
    {
        .config_file = "./conf/projectiles/projectile.json",
        .name = "projectile",
        .id = PROJECTILE,
        .type = PROJECTILES,
        .show = sfTrue,
        .init = &init_projectiles,
        .draw = &draw_projectiles,
        .destroy = &destroy_projectile,
    },
    // !PROJECTILE


    // MINI_MAP
    {
        .config_file = "./conf/mini_map/minimap.json",
        .name = "mini_map",
        .id = MINI_MAP,
        .type = SPRITE,
        .show = sfTrue,
        .init = &init_minimap,
        .draw = &draw_minimap,
        .destroy = &destroy_minimap,
    },
    // !MINI_MAP


    // DIALOG
    {
        .config_file = "./conf/dialogs/dialog_render.json",
        .name = "dialog_background",
        .id = DIALOG_BACKGROUND,
        .type = SPRITE,
        .show = sfFalse,
        .init = &init_sprite,
        .draw = &draw_sprite,
        .destroy = &destroy_sprite,
    },
    {
        .config_file = "./conf/dialogs/dialog_render.json",
        .name = "dialog_renderer",
        .id = DIALOG_RENDERER,
        .type = DIALOG,
        .show = sfFalse,
        .init = &init_dialog,
        .draw = &draw_dialog,
        .destroy = &destroy_dialog,
    },
    // !DIALOG
};

#endif /* !COMPONENTS_H_ */
